x-uffizzi:
  ingress:
    service: noaafetch
    port: 5000
  continuous_preview:
    deploy_preview_when_image_tag_is_created: true

services:
  noaafetch:
    image: uffizziqa.azurecr.io/noaafetch
  deploy:
    resources:
      limits:
        memory: 250M
