name: default

on: [push,pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: axisofentropy/noaafetch
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update Docker Hub Description for Default Branch
        uses: peter-evans/dockerhub-description@v2.4.3
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: axisofentropy/noaafetch
      - name: Deploy preview
        uses: UffizziCloud/preview-action@master
        with:
          compose-file: 'docker-compose.yaml'
          username: 'adam@idyl.tech'
          hostname: 'https://app.qa-gke.uffizzi.com'
          project: 'second-adam-zezw'
          password: ${{ secrets.UFFIZZI_PASSWORD }}
