name: default

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened,synchronize,reopened]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: axisofentropy/noaafetch
      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update Docker Hub Description for Default Branch
        uses: peter-evans/dockerhub-description@v2.4.3
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: axisofentropy/noaafetch
      - name: Prep temporary compose file.
        run: |
          mkdir ./tmp &&
          cat <<EOF > ./tmp/docker-compose.generated.yaml
          x-uffizzi:
            ingress:
              service: noaafetch
              port: 5000
            continuous_preview:
              deploy_preview_when_image_tag_is_created: true
          services:
            noaafetch:
              image: ${{ steps.meta.outputs.tags }}
              deploy:
                resources:
                  limits:
                    memory: 500M
          EOF
      - name: Deploy preview
        id: preview
        uses: UffizziCloud/preview-action@outputs
        with:
          compose-file: 'tmp/docker-compose.generated.yaml'
          username: 'admin@uffizzi.com'
          hostname: 'https://tmp-eks-2022-04.uffizzi.com/'
          project: 'default'
          password: ${{ secrets.UFFIZZI_PASSWORD }}
      - name: Check outputs
        run: echo "${{ steps.preview.outputs.id }} at ${{ steps.preview.outputs.url }}"
      - name: Comment on Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Deployed preview ID ${{ steps.preview.outputs.id }} at URL ${{ steps.preview.outputs.url }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
