name: default

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Deploy preview
        uses: UffizziCloud/preview-action@master
        with:
          compose-file: 'docker-compose.uffizzi.yml'
          username: 'adam@idyl.tech'
          hostname: 'https://app.qa-gke.uffizzi.com'
          project: 'second-adam-zezw'
          password: ${{ secrets.UFFIZZI_PASSWORD }}
